version: 1.0.29pre1-{build}
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
install:
  - if %platform%==Win32 set VCPKG_TRIPLET=x86-windows
  - if %platform%==x64 set VCPKG_TRIPLET=x64-windows
  - vcpkg install libogg:%VCPKG_TRIPLET% libvorbis:%VCPKG_TRIPLET% libflac:%VCPKG_TRIPLET% sqlite3:%VCPKG_TRIPLET% opus:%VCPKG_TRIPLET%
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - if %CONFIGURATION%=Debug set BUILD_SHARED_LIBS=ON
  - if %CONFIGURATION%=Release set BUILD_SHARED_LIBS=OFF
  - cmake .. -G"%CMAKE_GENERATOR%" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
build:
  project: c:\projects\libsndfile\CMakeBuild\sndfile.sln
  verbosity: minimal
for:
-
  matrix:
    only:
      - configuration: Debug
  test_script:
    - ctest -V
after_build:
  # - dir
  - 7z a ..\sndfile-%PLATFORM%-%CONFIGURATION%.zip "%APPVEYOR_BUILD_FOLDER%\CMakeBuild\%CONFIGURATION%\*.dll"
artifacts:
  - path: sndfile-%PLATFORM%-%CONFIGURATION%.zip
cache:
  C:\Tools\vcpkg\Installed -> appveyor.yml
